name: Changelog CI

on:
  release:
    types: [ published ]

  workflow_dispatch:
    inputs:
      release:
        description: 'Release'
        required: true
jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        id: changelog-ci
        with:
          config_file: ./.github/config/changelog-ci-config.yaml
          changelog_filename: CHANGELOG-changelog-ci.md
          release_version: ${{ github.event.release.tag_name || inputs.release }}
          github_token: ${{ secrets.token }}

      - name: Get context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Get Changelog Output
        run: |
          echo "${{ toJson(steps.changelog-ci.outputs) }}"

      - name: Get Changelog Output
        run: |
          echo $GITHUB_STEP_SUMMARY

      # - name: Merge Pull Request
      #   uses: juliangruber/merge-pull-request-action@v1
      #   with:
      #     github-token: ${{ secrets.token }}
      #     number: ${{github.event.pull_request.number}}
      #     method: squash # merge rebase
      #     repo: juliangruber/octokit-action

      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "[Changelog CI]"