name: Changelog CI

on:
  release:
    types: [ published ]

  workflow_dispatch:
    inputs:
      release:
        description: 'Release'
        required: true
jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          config_file: ./.github/config/changelog-ci-config.yaml
          changelog_filename: CHANGELOG-changelog-ci.md
          release_version: ${{ github.event.release.tag_name || inputs.release }}
          github_token: ${{ secrets.token }}

      - name: Get context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.token }}
          number: 1
          method: squash # merge rebase
          repo: juliangruber/octokit-action