name: Changelog CI

on:
  release:
    types: [ published ]

  workflow_dispatch:
    inputs:
      release:
        description: 'Release'
        required: true
jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        id: changelog-ci
        with:
          config_file: ./.github/config/changelog-ci-config.yaml
          changelog_filename: CHANGELOG-changelog-ci.md
          release_version: ${{ github.event.release.tag_name || inputs.release }}
          github_token: ${{ secrets.token }}

      - name: Get context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Get Changelog Output
        env:
          GITHUB_CI_OUTPUTS: ${{ toJson(steps.changelog-ci) }}
        run: |
          echo $GITHUB_CI_OUTPUTS

      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.token }}"
          MERGE_LABELS: "[Changelog CI]"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "Auto merge CHANGELOG.md"
          MERGE_DELETE_BRANCH: true
          MERGE_FORKS: "false"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_REQUIRED_APPROVALS: "0"
          UPDATE_LABELS: ""
          UPDATE_METHOD: "rebase"