name: Changelog
on:
  release:
    types: [created, edited]
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.token }}
          repo: 'ReggiardoJuan/gradleSelenium'
          output: CHANGELOG.md
      - run: |
          cat CHANGELOG.md
